# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.ManyToManyField(related_name='keywords', related_query_name='keyword', to='article.Keywords', verbose_name='Теги'),
        ),
    ]
