# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_article_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Категория'),
        ),
    ]
