# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 10:09
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160709_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_text',
            field=ckeditor.fields.RichTextField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='article_taxt',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
