# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 15:57
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20160716_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=150, verbose_name='Категория'),
        ),
    ]
