# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20160717_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
