# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_site_vkaldki'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vkaldki',
            new_name='Vkladki',
        ),
    ]
