# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-10 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_auto_20160719_1313'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='genre',
            managers=[
            ],
        ),
    ]
